### ISSUE TITLE
インポート時に不正な書式があるとエラー画面に遷移する

### ISSUE THREAD

**Issue by agilemasayuki** [agileware-jp/redmine_importer#4]
インポート時に不正な書式があるとエラー画面に遷移する（csvでは題名（文字入力）だが、インポートする際に「題名」の対応するフィールドを期日に変更してインポートする等）

**Comment by mozamimy** [comment]
CSV から取ってきたデータを日付に変換した場合に、変換できないような形式のデータが入ってると例外で落ちますね。
これは、エラーメッセージが表示されるように修正したほうがいいかなと思います。

**Comment by mozamimy** [comment]
これは直して PR 送りましょうか

**Comment by mozamimy** [comment]
https://github.com/agileware-jp/redmine_importer/pull/6
プルリクりました
