### ISSUE TITLE
チケットの更新が出来ない

### ISSUE THREAD

**Issue by agilemasayuki** [agileware-jp/redmine_importer#5]
チケットの更新が出来ない（ユニークフィールドに題名を選択）
（失敗した行数をみると同じ行が２つでてたりする）
http://gyazo.com/6f5cf89ce37497e908b7fd1ffb3493f7

**Comment by mozamimy** [comment]
これに関しては、機能していると思います。  
スクリーンショットを見ている感じだと、CSV ファイルの中のユニークフィールド（この場合だと題名）に同じ名前を設定していないでしょうか？  
あくまで**ユニーク**フィールドなので、ユニークでないならば失敗するのは仕様上そういうものだと思います。

**Comment by mozamimy** [comment]
追記です。
既に同じユニークフィールドをもつチケットが Redmine 上に存在するときにこの現象が起こりますね。
インポータの立場からするとどちらを更新したらいいかわからないので、失敗するのは仕方ないと思います。

**Comment by agilemasayuki** [comment]
仕様ということで問題ないそうです。
更新する際は、[id]をユニークフィールドに設定してcsvにも[id]列を作れば更新できるので[id]ベースで更新してもらうという形になります。
手順としては、チケット一覧から一旦csvでエクスポートしてそれを編集して、再インポートさせるという風になります。

今のままでも問題なさそうなのでクローズします。
